### ISSUE TITLE
Updates of JDK will break the buildpack

### ISSUE THREAD

**Issue by HDYA** [dmikusa-pivotal/cf-maven-buildpack#3]
Updates of JDK will cause the download to fail.

Maybe should consider OpenJDK or not-hard-coded link to JDK?

**Comment by dmikusa-pivotal** [comment]
It's been a really long time since I've looked at this, but I think you can override anything in this file https://github.com/dmikusa-pivotal/cf-maven-buildpack/blob/master/defaults/options.json from a file pushed with your application called `.bp-config/options.json`.

So you could put these three into your app's options.json file to use whatever JVM you want.

```
    "JAVA_DOWNLOAD_PREFIX": "http://download.oracle.com/otn-pub/java/jdk/7u72-b14/",
    "JAVA_PACKAGE": "jdk-7u72-linux-x64.tar.gz",
    "JAVA_PACKAGE_HASH": "cfa44b49e50ea06e5c6ab95ff79e5b2a"
```

**Comment by HDYA** [comment]
Thanks Daniel
